name: LuckyItem
version: "4.3"
main: com.nokhoon.luckyitem.PluginMain
description: Feeling lucky?
api-version: 1.18
author: "0x0804ac"
commands:
  crate:
    description: What's inside the crate? Open it and find out!
    usage: /crate (crate) [amount]
  rarity:
    description: Can I get this item from that crate? If yes, how often?
    usage: /rarity (crate) (item)
  supply:
    description: Interval for giving every online player a random crate
    usage: /supply [seconds]